/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_spark_examples_lqcd_ReadFileC */

#ifndef _Included_org_apache_spark_examples_lqcd_ReadFileC
#define _Included_org_apache_spark_examples_lqcd_ReadFileC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_spark_examples_lqcd_ReadFileC
 * Method:    readGaugeFiledC
 * Signature: (Ljava/lang/String;)Lorg/apache/spark/examples/lqcd/SU3Field;
 */
JNIEXPORT jobject JNICALL Java_org_apache_spark_examples_lqcd_ReadFileC_readGaugeFiledC
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
