/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_spark_blaze_NativeUtils */

#ifndef _Included_org_apache_spark_blaze_NativeUtils
#define _Included_org_apache_spark_blaze_NativeUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_spark_blaze_NativeUtils
 * Method:    rte
 * Signature: (I[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_apache_spark_blaze_NativeUtils_rte
  (JNIEnv *, jclass, jint, jobjectArray);

/*
 * Class:     org_apache_spark_blaze_NativeUtils
 * Method:    mpirun
 * Signature: (I[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_apache_spark_blaze_NativeUtils_mpirun
  (JNIEnv *, jclass, jint, jobjectArray);

/*
 * Class:     org_apache_spark_blaze_NativeUtils
 * Method:    test
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_apache_spark_blaze_NativeUtils_test
  (JNIEnv *, jclass);

/*
 * Class:     org_apache_spark_blaze_NativeUtils
 * Method:    setEnv
 * Signature: (Ljava/util/Map;)I
 */
JNIEXPORT jint JNICALL Java_org_apache_spark_blaze_NativeUtils_setEnv
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_apache_spark_blaze_NativeUtils
 * Method:    getEnv
 * Signature: ()Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_org_apache_spark_blaze_NativeUtils_getEnv__
  (JNIEnv *, jclass);

/*
 * Class:     org_apache_spark_blaze_NativeUtils
 * Method:    getEnv
 * Signature: (Ljava/lang/String;)Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_org_apache_spark_blaze_NativeUtils_getEnv__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
