/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_spark_mpi_NativeUtil */

#ifndef _Included_org_apache_spark_mpi_NativeUtil
#define _Included_org_apache_spark_mpi_NativeUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_spark_mpi_NativeUtil
 * Method:    namespaceFinalize
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_apache_spark_mpi_NativeUtil_namespaceFinalize
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_apache_spark_mpi_NativeUtil
 * Method:    namespaceQuery
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_apache_spark_mpi_NativeUtil_namespaceQuery
  (JNIEnv *, jclass);

/*
 * Class:     org_apache_spark_blaze_deploy_mpi_NativeUtils
 * Method:    setEnv
 * Signature: (Ljava/util/Map;)I
 */
JNIEXPORT jint JNICALL Java_org_apache_spark_mpi_NativeUtil_setEnv
(JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
