/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class A */

#ifndef _Included_A
#define _Included_A
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     A
 * Method:    a
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_A_a
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
