/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_A */

#ifndef _Included_org_A
#define _Included_org_A
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_A
 * Method:    a
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_A_a
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
