/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_spark_blaze_MPILauncher */

#ifndef _Included_org_apache_spark_blaze_MPILauncher
#define _Included_org_apache_spark_blaze_MPILauncher
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_spark_blaze_MPILauncher
 * Method:    prte
 * Signature: (I[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_apache_spark_blaze_MPILauncher_rte
  (JNIEnv *env, jclass cls, jint argc, jobjectArray argv);

JNIEXPORT jint JNICALL Java_org_apache_spark_blaze_MPILauncher_mpirun
        (JNIEnv *env, jclass cls, jint argc, jobjectArray argv);

#ifdef __cplusplus
}
#endif
#endif
