/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
//#include "prte.c"
/* Header for class org_apache_spark_blaze_MPILauncher */
#ifndef _Included_org_apache_spark_blaze_MPILauncher
#define _Included_org_apache_spark_blaze_MPILauncher
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_spark_blaze_MPILauncher
 * Method:    prte
 * Signature: (I[Ljava/lang/String;)I
 */


JNIEXPORT jint JNICALL Java_org_apache_spark_blaze_MPILauncher_prte
  (JNIEnv * env, jclass cls, jint argc, jobjectArray argv){
    const char *pargv[argc] = NULL;
    int stringCount = (*env)->GetArrayLength(env, argv);
    for(int i=0; i<stringCount; i++){
        jstring string = (*env)->GetObjectArrayElement(env, argv,i);
        pargv[i] = (*env)->GetStringUTFChars(env, string, NULL);
    }
    while(*pargv != NULL){
        printf("pargv is %d", *pargv);
        pargv++;
    }
    prte(argc,pargv);
    }




#ifdef __cplusplus
}
#endif
#endif
